source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '8.0'
use_frameworks!
target 'AliyunPlayerDemo' do
    pod 'AliyunPlayer_iOS/AliyunVodPlayerSDK'
    pod 'SDWebImage'
    pod 'Dic2CoreDataAutoWriter'
    pod 'Reachability'
end
